config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'home#index'
  get 'my_courses', to: 'home#my_courses'

  get 'sign_up', to: 'registrations#new'
  post 'sign_up', to: 'registrations#create'

  get 'log_in', to: 'sessions#new'
  post 'log_in', to: 'sessions#create'
  delete 'log_out', to: 'sessions#destroy'

  namespace :admin do
    resources :courses
    root to: 'courses#index'
  end

  mount ApiRoot => ApiRoot::PREFIX
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
# frozen_string_literal: true

class Course < ApplicationRecord
  has_many :purchased_courses
  has_many :users, through: :purchased_courses

  enum status: { unpublished: 0, published: 1 }, _prefix: true
  enum currency: { twd: 0, cny: 1, jpy: 2, hkd: 3, usd: 4 }, _prefix: true
  enum category: { chinese: 0, english: 1, math: 2, physics: 3, history: 4 }, _prefix: true

  validates :subject, presence: true, uniqueness: true

  validates :currency, :category, :status, :description, presence: true

  validates :price,
            presence: true,
            numericality: { greater_than_or_equal_to: 0 }

  validates :valid_day,
            presence: true,
            numericality: { only_integer: true,
                            greater_than_or_equal_to: 1,
                            less_than_or_equal_to: 31 }

  scope :detail, ->(ids) { where(id: ids) }
  scope :by_category, ->(value) { where(category: value) }
end

app/models/current.rb
# frozen_string_literal: true

class Current < ActiveSupport::CurrentAttributes
  attribute :user
end

app/models/purchased_course.rb
# frozen_string_literal: true

class PurchasedCourse < ApplicationRecord
  belongs_to :user
  belongs_to :course
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_secure_password

  has_many :purchased_courses
  has_many :courses, through: :purchased_courses

  validates :first_name, presence: true
  validates :last_name, presence: true

  validates :email,
            presence: true,
            uniqueness: true,
            format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }

  validates :password_digest,
            presence: true,
            confirmation: true,
            length: { minimum: 8 }
end

app/controllers/admin/base_controller.rb
# frozen_string_literal: true

class Admin::BaseController < ApplicationController
  before_action :authenticate_user
  before_action :authenticate_admin

  private

  def authenticate_user
    redirect_to root_path, alert: t('user_not_allowed') if Current.user.nil?
  end

  def authenticate_admin
    redirect_to root_path, alert: t('user_not_allowed') if Current.user.admin == false
  end
end

app/controllers/admin/courses_controller.rb
# frozen_string_literal: true

class Admin::CoursesController < Admin::BaseController
  before_action :find_course, only: %i[show edit update destroy]

  def index
    @courses = Course.all
  end

  def show; end

  def new
    @course = Course.new
  end

  def create
    @course = Course.new(course_params)

    if @course.save
      redirect_to admin_root_path, notice: t('.success')
    else
      render :new
    end
  end

  def edit; end

  def update
    if @course.update(course_params)
      redirect_to admin_root_path, notice: t('.success')
    else
      render :edit
    end
  end

  def destroy
    if @course.destroy
      redirect_to admin_root_path, notice: t('.success')
    else
      flash[:alert] = t('.fail')
      render :index
    end
  end

  private

  def course_params
    params.require(:course).permit(:subject,
                                   :price,
                                   :currency,
                                   :category,
                                   :status,
                                   :url,
                                   :description,
                                   :valid_day)
  end

  def find_course
    @course = Course.find_by(id: params[:id])
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :set_current_user, :set_locale

  private

  def set_current_user
    Current.user = User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def set_locale
    session[:locale] = params[:locale] if params[:locale] && I18n.available_locales.include?(params[:locale].to_sym)

    I18n.locale = session[:locale] || I18n.default_locale
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  before_action :init_course, only: :index
  before_action :set_my_course, only: :my_courses

  def index; end

  def my_courses; end

  def init_course
    @courses = Course.status_published
  end

  def set_my_course
    user_course = Current.user.purchased_courses
    course_ids = user_course.map(&:course_id)
    @courses = Course.where(id: course_ids)
  end
end

app/controllers/registrations_controller.rb
# frozen_string_literal: true

class RegistrationsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_path, notice: t('.success')
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < ApplicationController
  def new; end

  def create
    user = User.find_by(email: params[:email])
    if user.present? && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path, notice: t('.success')
    else
      flash[:alert] = t('.fail')
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: t('.success')
  end
end

app/helpers/admin/courses_helper.rb
# frozen_string_literal: true

module Admin::CoursesHelper
  def options_for_category
    options_for_select(Course.categories.keys.map { |k| [t("course_category.#{k}"), k] }, @course.category)
  end

  def options_for_status
    options_for_select(Course.statuses.keys.map { |k| [t("course_status.#{k}"), k] }, @course.status)
  end

  def options_for_currency
    options_for_select(Course.currencies.keys.map { |k| [t("course_currency.#{k}"), k] }, @course.currency)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/admin/courses/_form.html.erb
<%= form_for [:admin, @course] do |form| %>
  <% if @course.errors.any? %>
    <div class='alert alert-danger'>
      <% @course.errors.full_messages.each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>
  <% end %>

  <div class='col-12 mb-3'>
    <%= form.label :subject, class: 'form-label' %>
    <%= form.text_field :subject, class: 'form-control' %>
  </div>

  <div class='col-12 mb-3'>
    <%= form.label :category, class: 'form-label' %>
    <%= form.select :category, options_for_category, {}, class: 'form-select' %>
  </div>

  <div class='col-12 mb-3'>
    <%= form.label :status, class: 'form-label' %>
    <%= form.select :status, options_for_status, {}, class: 'form-select' %>
  </div>

  <div class='col-12 mb-3'>
    <%= form.label :valid_day, class: 'form-label' %>
    <%= form.number_field :valid_day, class: 'form-control' %>
  </div>

  <div class='col-12 mb-3'>
    <%= form.label :url, class: 'form-label' %>
    <%= form.text_field :url, class: 'form-control' %>
  </div>

  <div class='col-12 mb-3'>
    <%= form.label :currency, class: 'form-label' %>
    <%= form.select :currency, options_for_currency, {}, class: 'form-select' %>
  </div>

  <div class='col-12 mb-3'>
    <%= form.label :price, class: 'form-label' %>
    <%= form.number_field :price, min: 0, step: 0.01, class: 'form-control' %>
  </div>

  <div class='col-12 mb-3'>
    <%= form.label :description, class: 'form-label' %>
    <%= form.text_area :description, class: 'form-control' %>
  </div>

  <div class='mb-3'>
    <%= form.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/admin/courses/edit.html.erb
<h2 class='mt-3 mb-3'><%= t('edit_course') %></h2>

<%= render partial: 'admin/courses/form' %>

app/views/admin/courses/index.html.erb
<h2 class='mt-3 mb-3'><%= t('admin_page') %></h2>

<%= link_to t('new_course'), new_admin_course_path, class: 'btn btn-primary' %>

<table class='table table-hover'>
  <thead>
    <tr>
      <td><%= t('activerecord.attributes.course.id') %></td>
      <td><%= t('activerecord.attributes.course.subject') %></td>
      <td><%= t('activerecord.attributes.course.category') %></td>
      <td><%= t('activerecord.attributes.course.status') %></td>
      <td><%= t('activerecord.attributes.course.valid_day') %></td>
      <td><%= t('activerecord.attributes.course.currency') %></td>
      <td><%= t('activerecord.attributes.course.price') %></td>
    </tr>
  </thead>
  <tbody>
    <tr>
      <% @courses.each do |course| %>
        <th scope='row'><%= course.id %></th>
          <td><%= link_to course.subject, admin_course_path(course) %></td>
          <td><%= t("course_category.#{course.category}") %></td>
          <td><%= t("course_status.#{course.status}") %></td>
          <td><%= t('label_day', day: course.valid_day) %></td>
          <td><%= t("course_currency.#{course.currency}") %></td>
          <td><%= course.price.to_f %></td>
          <td><%= link_to t('label_edit'),
                          edit_admin_course_path(course),
                          class: 'btn btn-success' %>
          </td>
          <td><%= link_to t('label_delete'),
                          admin_course_path(course),
                          method: :delete,
                          data: { confirm: t('admin.courses.destroy.confirm') },
                          class: 'btn btn-danger' %>
          </td>
        </tr>
      <% end %>
  </tbody>
</table>

app/views/admin/courses/new.html.erb
<h2 class='mt-3 mb-3'><%= t('new_course') %></h2>

<%= render partial: 'admin/courses/form' %>

app/views/admin/courses/show.html.erb
<h2 class='mt-3 mb-3'><%= t('show_course') %></h2>

<table class='table'>
  <thead>
    <tr>
      <th><%= t('activerecord.attributes.course.id') %></th>
      <th><%= @course.id %></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= t('activerecord.attributes.course.subject') %></td>
      <td><%= @course.subject %></td>
    </tr>
    <tr>
      <td><%= t('activerecord.attributes.course.category') %></td>
      <td><%= t("course_category.#{@course.category}") %></td>
    </tr>
    <tr>
      <td><%= t('activerecord.attributes.course.status') %></td>
      <td><%= t("course_status.#{@course.status}") %></td>
    </tr>
    <tr>
      <td><%= t('activerecord.attributes.course.valid_day') %></td>
      <td><%= t('label_day', day: @course.valid_day) %></td>
    </tr>
    <tr>
      <td><%= t('activerecord.attributes.course.url') %></td>
      <td><%= @course.url %></td>
    </tr>
    <tr>
      <td><%= t('activerecord.attributes.course.currency') %></td>
      <td><%= t("course_currency.#{@course.currency}") %></td>
    </tr>
    <tr>
      <td><%= t('activerecord.attributes.course.price') %></td>
      <td><%= @course.price.to_f %></td>
    </tr>
    <tr>
      <td><%= t('activerecord.attributes.course.description') %></td>
      <td class='text-wrap'>
        <p><%= @course.description %></p>
      </td>
    </tr>
  </tbody>
</table>

<div class='d-flex justify-content-end'>
  <div>
    <%= link_to t('label_edit'),
                edit_admin_course_path(@course),
                class: 'btn btn-success' %>
  </div>

  <div class='ms-3'>
    <%= link_to t('label_delete'),
                admin_course_path(@course),
                method: :delete,
                data: { confirm: t('admin.courses.destroy.confirm') },
                class: 'btn btn-danger' %>
  </div>

  <div class='ms-3'>
    <%= link_to t('label_back'), :back, class: 'btn btn-light' %>
  </div>
</div>

app/views/home/_list.html.erb
<table class='table table-hover'>
  <thead>
    <tr>
      <td><%= t('activerecord.attributes.course.id') %></td>
      <td><%= t('activerecord.attributes.course.subject') %></td>
      <td><%= t('activerecord.attributes.course.category') %></td>
      <td><%= t('activerecord.attributes.course.status') %></td>
      <td><%= t('activerecord.attributes.course.valid_day') %></td>
      <td><%= t('activerecord.attributes.course.currency') %></td>
      <td><%= t('activerecord.attributes.course.price') %></td>
    </tr>
  </thead>
  <tbody>
    <tr>
      <% @courses.each do |course| %>
        <th scope='row'><%= course.id %></th>
          <td><%= course.subject %></td>
          <td><%= t("course_category.#{course.category}") %></td>
          <td><%= t("course_status.#{course.status}") %></td>
          <td><%= t('label_day', day: course.valid_day) %></td>
          <td><%= t("course_currency.#{course.currency}") %></td>
          <td><%= course.price.to_f %></td>
        </tr>
      <% end %>
  </tbody>
</table>

app/views/home/_my_list.html.erb
<table class='table table-hover'>
  <thead>
    <tr>
      <td><%= t('activerecord.attributes.course.id') %></td>
      <td><%= t('activerecord.attributes.course.subject') %></td>
      <td><%= t('activerecord.attributes.course.category') %></td>
      <td><%= t('activerecord.attributes.course.status') %></td>
      <td><%= t('label_expiry_at') %></td>
      <td><%= t('activerecord.attributes.course.currency') %></td>
      <td><%= t('activerecord.attributes.course.price') %></td>
    </tr>
  </thead>
  <tbody>
    <tr>
      <% @courses.each do |course| %>
        <th scope='row'><%= course.id %></th>
          <td><%= course.subject %></td>
          <td><%= t("course_category.#{course.category}") %></td>
          <td><%= t("course_status.#{course.status}") %></td>
          <td>
            <%= course.purchased_courses.find_by(user_id: Current.user).expiry_at %>
          </td>
          <td><%= t("course_currency.#{course.currency}") %></td>
          <td><%= course.price.to_f %></td>
        </tr>
      <% end %>
  </tbody>
</table>

app/views/home/index.html.erb
<h2 class='mt-3 mb-3'><%= t('courses') %></h2>

<%= render partial: 'home/list' %>

app/views/home/my_courses.html.erb
<h2 class='mt-3 mb-3'><%= t('my_courses') %></h2>

<%= render partial: 'home/my_list' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ELearning</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: 'shared/navbar' %>

    <div class="container">
      <%= render partial: 'shared/flash' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
  <div class='alert alert-info mt-4' role='alert'>
    <%= flash[:notice] %>
  </div>
<% end %>

<% if flash[:alert] %>
  <div class='alert alert-warning mt-4' role='alert'>
    <%= flash[:alert] %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class='navbar navbar-expand-lg navbar-light bg-light'>
  <div class='container-fluid'>
    <%= link_to t('e_learning'), root_path, class: 'navbar-brand'%>
    <div class='navbar-nav'>
      <% if Current.user %>
        <%= link_to t('my_courses'), my_courses_path, { class: 'nav-link' } %>
      <% end %>
    </div>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <%= t('language') %>
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><%= link_to t('traditional_chinese'), {locale: 'zh-TW'}, {class: 'dropdown-item'} %></li>
            <li><hr class="dropdown-divider"></li>
            <li><%= link_to t('english'), {locale: 'en'}, {class: 'dropdown-item'} %></li>
          </ul>
        </li>
      </ul>
    </div>

    <div class='navbar-nav'>
      <% if Current.user %>
        <span class='navbar-text fw-bold'><%= t('hello', name: Current.user.last_name) %></span>
        <% if Current.user.admin %>
          <%= link_to t('admin_page'), admin_root_path, class: 'nav-link' %>
        <% end %>
        <%= link_to t('log_out'), log_out_path, method: :delete, class: 'nav-link' %>
      <% else %>
        <%= link_to t('sign_up'), sign_up_path, class: 'nav-link' %>
        <%= link_to t('log_in'), log_in_path, class: 'nav-link' %>
      <% end %>
    </div>
  </div>
</nav>